### ISSUE TITLE
What does it work better: one_step mode or not one_step mode?

### ISSUE THREAD

**Issue by avostryakov** [julianser/hed-dlg-truncated#12]
In one_step mode, you process every utterance in a dialogue separately and pass a previous hidden state to the next initial hidden state of the next utterance.It looks like it is the same like process all utterances in a dialogue in a single sequence.

  By the way, can you process several utterances from several dialogues in the utterance encoder? Is there this mode?

P.S. Sorry that I ask by creating an issue. I thought that it appropriate to ask near the code.

**Comment by julianser** [comment]
one_step mode is designed for processing ONE single token (i.e. the next token in an utterance).

The UtteranceEncoder is designed for processing one utterance at a time, but in principle you can apply to any sequence of words (even a full dialogue).
