### ISSUE TITLE
What does "max_length" mean?

### ISSUE THREAD

**Issue by dimeldo** [julianser/hed-dlg-truncated#13]
What does the "max_length" parameter mean? Is it the maximum number of _tokens_ in a _single utterance_? The maximum number of _characters_ in a _single utterance_? The maximum number of _tokens_ in all the _contexts utterances_?

Sorry for newbie question, just trying to figure it out.

**Comment by julianser** [comment]
It's the length of the longest dialogue in a batch.

**Comment by dimeldo** [comment]
@julianser length in characters or words?
