### ISSUE TITLE
how to test?

### ISSUE THREAD

**Issue by billy800413** [julianser/hed-dlg-truncated#14]
i download the Datasets " The pre-processed Ubuntu Dialogue Corpus and model responses used by Serban et al".  follow the Model Training step and put "Dataset.dict.pkl" "Test.dialogues.pkl" "Training.dialogues.pkl" "Validation.dialogues.pkl" to the Data folder.
run "THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python train.py --prototype  prototype_ubuntu_HRED> Model_Output.txt"
it return "No such file or directory: '../UbuntuData/Dataset.dict.pkl' "
Did I miss anything?

**Comment by dimeldo** [comment]
You should change these in the `state.py` to your own directory (Data/Training.dialogues.pkl, etc...):
```
state['train_dialogues'] = "../UbuntuData/Training.dialogues.pkl"
state['test_dialogues'] = "../UbuntuData/Test.dialogues.pkl"
state['valid_dialogues'] = "../UbuntuData/Validation.dialogues.pkl"
state['dictionary'] = "../UbuntuData/Dataset.dict.pkl"
```
