### ISSUE TITLE
Request for the movie dataset

### ISSUE THREAD

**Issue by jamesweb1** [julianser/hed-dlg-truncated#5]
Hi, I find it interesting of this project. I know dataset in the paper is from Movie-DiC, and it is developed as MovieTriples dataset. I find it's difficult to get the dataset on the internet. Can you provide it to me privately for my personal research? I'll appreciate for it :)

BTW, If I use the movie dataset you provide, can I use "prototype_movies" to make it work?
I find  `state['pretrained_word_embeddings_file']` = './tests/data/MT_WordEmb.pkl' ` in the prototype, where does this come from? should I use this file?

Sorry for posting here cause I cannot get the contact info. Hope to see your response, thanks.

**Comment by julianser** [comment]
Hi James, can you please forward your request to my email: julian DOT serban AT gmail DOT com?

**Comment by SeekPoint** [comment]
@julianser I will send the request email to you, is this OK?

**Comment by maxindian** [comment]
can you give the dataset to me ? thanks my email :  maxindian666 AT outlook DOT com

**Comment by linxiaoby** [comment]
can you please give me the MovieTriples dataset, thanks.
My email：  wlpku AT pku DOT edu DOT cn

**Comment by zahra-sayedi** [comment]
would you please send me your movie dataset?
thank you a lot
my email address: zahrasayedi95@gmail.com

**Comment by evelinehong** [comment]
Would you please send me ur movie dataset?
email: evelinehong@sjtu.edu.cn
thx a lot

**Comment by SarikGhazarian** [comment]
Julian,

could you please send me Movie-Triples dataset as well. I really appreciate it.
my email: sarikgha@usc.edu

**Comment by Pranav-Goel** [comment]
Hi Julian, I'd really appreciate it if you could share the Movie-Triples dataset. This is for a research project and of course, the paper will be duly cited. 
email: pgoel1@cs.umd.edu

**Comment by qichaotang** [comment]
Julian,

could you please send me Movie-Triples dataset as well. I really appreciate it.
my email: qichaotang97@163.com

**Comment by joeysobat** [comment]
Hi,
Could you please sand me the Movie-Triples dataset for a research project? It would be much appreciated, thank you.
My email: an.munarriz07@gmail.com

**Comment by manzar96** [comment]
Julian,

Could you please send me Movie-Triples dataset for a research project? I really appreciate it. Thanks in advance.
my email: el14798@central.ntua.gr or  manoszar96@gmail.com

**Comment by dalderop** [comment]
Could you please send me the dataset for my project> My email is Pieter.dalderop@caiway.net.

Many thanks!

**Comment by hieuchi911** [comment]
Hi,
I really need Movie Triples dataset for my current research project. Could you please send me the dataset? Really appreciate it.
This is my email: hieuhocnlp@gmail.com

Thank you
