### ISSUE TITLE
ImportError: No module named scan

### ISSUE THREAD

**Issue by SeekPoint** [julianser/hed-dlg-truncated#9]
rzai@rzai00:~/prj/hed-dlg-truncated$ THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python train.py --prototype prototype_ubuntu_HRED > Model_Output.txt
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from dialog_encdec import *
  File "/home/rzai/prj/hed-dlg-truncated/dialog_encdec.py", line 16, in <module>
    from theano.sandbox.scan import scan
ImportError: No module named scan
rzai@rzai00:~/prj/hed-dlg-truncated$ 
rzai@rzai00:~/prj/hed-dlg-truncated$ 
rzai@rzai00:~/prj/hed-dlg-truncated$ ll

**Comment by julianser** [comment]
Fixed.
